# Generated by Django 5.2.3 on 2025-06-23 03:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('size', models.CharField(choices=[('startup', 'Startup (1-10 employees)'), ('small', 'Small (11-50 employees)'), ('medium', 'Medium (51-200 employees)'), ('large', 'Large (201-1000 employees)'), ('enterprise', 'Enterprise (1000+ employees)')], default='startup', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial_expired', 'Trial Expired')], default='active', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_bridges', models.PositiveIntegerField(default=3)),
                ('max_ai_requests_per_month', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='companies_slug_e0676c_idx'), models.Index(fields=['domain'], name='companies_domain_60b9fc_idx'), models.Index(fields=['status'], name='companies_status_2cde5e_idx'), models.Index(fields=['plan'], name='companies_plan_0bd0ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_enabled', models.BooleanField(default=True)),
                ('ai_provider', models.CharField(choices=[('google', 'Google Gemini'), ('openai', 'OpenAI')], default='google', max_length=20)),
                ('ai_model', models.CharField(default='gemini-pro', max_length=50)),
                ('ai_temperature', models.FloatField(default=0.7)),
                ('ai_max_tokens', models.IntegerField(default=1000)),
                ('message_retention_days', models.PositiveIntegerField(default=90)),
                ('auto_archive_days', models.PositiveIntegerField(default=30)),
                ('email_notifications', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('webhook_events', models.JSONField(blank=True, default=list)),
                ('require_2fa', models.BooleanField(default=False)),
                ('allowed_ip_ranges', models.JSONField(blank=True, default=list)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=480)),
                ('matrix_room_prefix', models.CharField(default='company', max_length=50)),
                ('auto_create_rooms', models.BooleanField(default=True)),
                ('bridge_auto_reconnect', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
            options={
                'db_table': 'company_settings',
            },
        ),
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('agent', 'Agent'), ('viewer', 'Viewer')], default='agent', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='companies.company')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_invitations',
                'indexes': [models.Index(fields=['token'], name='company_inv_token_a333e7_idx'), models.Index(fields=['status'], name='company_inv_status_a1f7b8_idx'), models.Index(fields=['expires_at'], name='company_inv_expires_60cc22_idx')],
                'unique_together': {('company', 'email')},
            },
        ),
    ]
