# Generated by Django 5.2.3 on 2025-06-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='auto_response_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
