[phases.setup]
nixPkgs = ["...", "python310", "postgresql", "gcc"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["PYTHONPATH=. python nexus_back/manage.py collectstatic --noinput", "PYTHONPATH=. python nexus_back/manage.py migrate"]

[start]
cmd = "python -m daphne -b 0.0.0.0 -p $PORT nexus_back.asgi:application"
