[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "python -m daphne -b 0.0.0.0 -p $PORT nexus_back.asgi:application"
healthcheckPath = "/api/health-check/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
