services:
  # Django веб-сервис
  - type: web
    name: nexus-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p $PORT nexus_back.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        fromDatabase:
          name: nexus-db
          property: connectionString
          key: DJANGO_SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://nexus-contact-center.vercel.app,http://localhost:3000"

  # Celery worker
  - type: worker
    name: nexus-celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A nexus_back worker -l info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: nexus-redis
          property: connectionString

  # Redis для каналов и Celery
  - type: redis
    name: nexus-redis
    ipAllowList: []
    plan: free

databases:
  # PostgreSQL база данных
  - name: nexus-db
    ipAllowList: []
