# Generated by Django 5.2.3 on 2025-06-23 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('conversations_handled', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('avg_response_time', models.DurationField(blank=True, null=True)),
                ('customer_rating', models.FloatField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('agent', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ConversationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('platform', models.CharField(max_length=50)),
                ('total_conversations', models.IntegerField(default=0)),
                ('new_conversations', models.IntegerField(default=0)),
                ('active_conversations', models.IntegerField(default=0)),
                ('closed_conversations', models.IntegerField(default=0)),
                ('avg_response_time', models.DurationField(blank=True, null=True)),
                ('customer_satisfaction_score', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_metrics', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'date', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='MessageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('platform', models.CharField(max_length=50)),
                ('total_messages', models.IntegerField(default=0)),
                ('incoming_messages', models.IntegerField(default=0)),
                ('outgoing_messages', models.IntegerField(default=0)),
                ('ai_responses', models.IntegerField(default=0)),
                ('human_responses', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_metrics', to='companies.company')),
            ],
            options={
                'unique_together': {('company', 'date', 'platform')},
            },
        ),
    ]
