# Generated by Django 5.2.3 on 2025-06-23 03:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('keyword', 'Keyword Match'), ('intent', 'Intent Recognition'), ('business_hours', 'Business Hours'), ('new_conversation', 'New Conversation'), ('inactivity', 'Inactivity')], max_length=50)),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('action_type', models.CharField(choices=[('send_message', 'Send Message'), ('assign_agent', 'Assign Agent'), ('tag_conversation', 'Tag Conversation'), ('escalate', 'Escalate'), ('ai_response', 'AI Response')], max_length=50)),
                ('action_parameters', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
