# Generated by Django 5.2.3 on 2025-06-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
